apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/spring:local
          imagePullPolicy: Never
