apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-app
  namespace: default
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: "poll"
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - image: ghcr.io/hoban4336/spring.io:latest # ghcr.io/your-github-username/your-repository:latest
          ports:
          - containerPort: 8080